AWSTemplateFormatVersion: '2010-09-09'
Description: Static site on S3 behind CloudFront with OAC
Parameters:
  DomainName:
    Type: String
    Description: Root domain (e.g., freegolffitting.com)
  AlternateNames:
    Type: CommaDelimitedList
    Default: www.freegolffitting.com
    Description: Additional domain names (comma-separated)
  CertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1 covering all domains
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DomainName}-site'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      Name: !Sub '${DomainName}-oac'
      OriginAccessControlConfig:
        Name: !Sub '${DomainName}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: !Split [",", !Join [",", [!Ref DomainName, !Join [",", !Ref AlternateNames]] ] ]
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultCacheBehavior:
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          ResponseHeadersPolicyId: eaab4381-ed33-4a86-88ca-d9558dc6cd63 # CORS-S3Origin
        Origins:
          - Id: s3origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt OAC.Id
Outputs:
  BucketName:
    Value: !Ref SiteBucket
  DistributionId:
    Value: !Ref Distribution
  DistributionDomain:
    Value: !GetAtt Distribution.DomainName
